### ISSUE TITLE
Broken dist

### ISSUE THREAD

**Issue by thesec** [dandehavilland/mg-line-brushing#17]
lines 222, 223
`var xValX0 = xScale.invert(extendX0);
        var xValX1 = xScale.invert(extendX1);`

should be
`var xValX0 = xScale.invert(extentX0);
        var xValX1 = xScale.invert(extentX1);`

... find your addon back working again when they are :)

**Comment by dandehavilland** [comment]
Thanks, I'll look into fixing and rebuilding.
