### ISSUE TITLE
Inconsistent package in npm

### ISSUE THREAD

**Issue by omnibs** [dandehavilland/mg-line-brushing#20]
Something is weird in the NPM package for `mg-line-brushing`:

```
$ npm install mg-line-brushing
$ cd node_modules/mg-line-brushing
$ cat package.json | grep version
  "version": "0.0.5"
$ cat dist/mg_line_brushing.js | grep time.d
            resolution = d3.time.day;
```

We got version 0.0.5 with the .js in `dist` as it was before [this commit](https://github.com/dandehavilland/mg-line-brushing/commit/c40f1063c37b2284f92c6cea22642f3bb1a63d6d).

**Comment by dandehavilland** [comment]
That's fixed - changes published in v0.0.6
