### ISSUE TITLE
Brushing is slow like hell. +23 Seconds

### ISSUE THREAD

**Issue by sinky** [dandehavilland/mg-line-brushing#21]
![chrome dev tools performance](https://user-images.githubusercontent.com/822246/34494863-a6f59fac-eff2-11e7-89db-6f7d1fd7f248.png)

Any idea why this happens? Brushing takes over 23 Seconds.

https://lab.my-azur.de/steps/brushing_demo.html

d3.js 4.7.2
metrics-graphics 2.11.0
mg-line-brushing latest
1424 data points

**Comment by dandehavilland** [comment]
I did a quick profile in the devtools and it seems MG struggles when animating a line for a dataset of this size. [This tween]( https://github.com/mozilla/metrics-graphics/blob/7b2f88189da8fcba055a4e9af75fe19b837144eb/src/js/misc/transitions.js#L17) is the source of the slowdown.

Disable smooth transitions by setting `transition_on_update: false` in `MG_options` and it'll update instantly.
