### ISSUE TITLE
Brushing when multiple graphs are displayed

### ISSUE THREAD

**Issue by shmul** [dandehavilland/mg-line-brushing#3]
Hi,

I encountered a weird bug - I have a page with 3 graphs, G1, G2, G3 displayed side by side. If I zoom into G1 for example, and then try to zoom into G3, then the brushing effect will be drawn on G3, yet upon mouse up G1 will be redrawn. It is consistent - the first graph on which zooming occurs will get all the zoom operations from the other graphs. I tried debugging the code and couldn't find the culprit. A wild guess - it might have to do with some "global" args properties (like brushed_max_x and brushed_max_y).

Other than that - cool plugin.

**Comment by dandehavilland** [comment]
Thanks for the report. I've replicated this - looks like it's down to some global leakage as you've suggested. Will look into it.

**Comment by dandehavilland** [comment]
This is fixed in v0.0.3.
