### ISSUE TITLE
publishing mg-line-brushing

### ISSUE THREAD

**Issue by hugocruz** [dandehavilland/mg-line-brushing#4]
Hello, 

I've been playing with your addon, and I really like it. My question, is about your plans of publishing it, being bower/npm. 

Again, thanks for the addon!

**Comment by dandehavilland** [comment]
Hi @hugocruz - thanks for the feedback! I have just registered it with bower and updated the README to reflect that.

**Comment by hugocruz** [comment]
Thank you !

**Comment by blazkovicz** [comment]
Hello, how about adding this project to npm?

**Comment by dandehavilland** [comment]
Published to npm.
